### ISSUE TITLE
Running on the background

### ISSUE THREAD

**Issue by alsanchez-dev** [thunkable/thunkable-issues#1011]
**Is your feature request related to a problem? Please describe.**
I'm using the radio video component to stream a radio station, this is a mobile app for a client. The music stops when the app is on the background

**Describe the solution you'd like**
I use Thunkable PRO annual plan so have live chat support, they have been telling us Thunkable apps does not run in the background, Thunkable apps shall run in the background 

**Describe alternatives you've considered**
None apart of the web browser component which also stops on iOS

**Which platform are you asking for?**
ThunkableX

**Additional context**
Hopefully, you guys can address this, I think many users are having the same issue. I think is a must, in order to have a professional tool to build mobile applications.

**Comment by jane-d-alt** [comment]
Hi there, thanks for this feature request.

We are aware that the community is interested in apps that run in the background. This would be a large technical task, and would require considerable planning and dev resources.

I'll bring it up to the team again, and see if we can include it in our quarterly planning. This is not a feature that would become available in the short term, but I'll see if dev time can be devoted to it in the medium term.

Since this feature request is open in issue #459, I'm going to close this request to avoid duplicates. I will act on this new request, but any updates will be shared in #459.

Thanks!
