### ISSUE TITLE
Apps Refuse To Open/Load Correctly.

### ISSUE THREAD

**Issue by Megalaoofania** [thunkable/thunkable-issues#1012]
### Platform
✕ Android companion (Moto G Play running Android 10)

### Issue/Request Origin
When trying to launch my app on my phone. (It worked for awhile)

### Steps to Reproduce
1. Log In
2. Enter A Project (and fail)
(Code Generated Way)
1. Enter Code On Computer
2. Refuses to load anything else.

### Project Link
https://x.thunkable.com/copy/93eb3f48eb6468ca7833599457c454e7 (IT DOES NOT ACTUALLY GIVE YOU MONEY, IT'S JUST A TEST OF HOW WELL I CAN CODE AND USE GOOGLE FIREBASE)

### Expected Behavior
Load normally and function completely fine. 

### Actual Behavior
Nothing happens / Breaks and doesn't work

(Finally got in via code generation, this is the result)

https://user-images.githubusercontent.com/83192893/130385897-7873e34d-75ac-4929-8d27-3d1682b8ea41.png

I am running the latest version of Thunkable Live, am I doing something wrong or is there a bug?

**Comment by Megalaoofania** [comment]
Nevermind, my messy coding may of caused this issue, but if anybody else has the same issue or if one of the staff may think it could be a potential problem, I'm keeping this open.

**Comment by jane-d-alt** [comment]
Hi there,

I'm glad to see you were able to test your project with the Thunkable Live app.
We haven't heard any reports of the Thunkable Live app crashing for users.
Since you figure this behavior was caused by your code, and we haven't heard other reports of the Live app crashing, I'm going to close this issue for now.

If you experience any future issues with the Thunkable Live app, or any individual components/blocks, please let us know.

Thanks,
Jane
