### ISSUE TITLE
Please enrich textbox functionality

### ISSUE THREAD

**Issue by lisztomania1** [thunkable/thunkable-issues#111]
1.) I use a textbox as a search field. To make the user experience comparable to the safari browser searching, I need a event block, which is triggered by using the "open" button on the keyboard.

2.) please let us make keyboards vanish (when button is clicked -> textbox1.hideKeyboard)

3.) textbox. get focus 

all these are already available on thunkable android

any response highly appreciated!

**Comment by lflfm** [comment]
I'll just add that I think this (plus related issue #92) should be VERY HIGH priority.
User input is so important for most apps and currently the textbox is almost unusable from UX point of view - our users will be very quickly frustrated with the textbox experience.
(because of this, as it stands I cannot use Thunkable in a production environment if any sort of user text input is required...)

**Comment by jane-d-alt** [comment]
Text Input now has the following events:
When Text Input Click
When Text Input Changes
When Text Input Unfocus
When Text Input Submit

You can find the 'hide keyboard' block in the device blocks: https://docs.thunkable.com/device#dismiss-keyboard

We'll close this issue now; apologies for not following up when these blocks were originally added.
