### ISSUE TITLE
Web API PATCH method

### ISSUE THREAD

**Issue by lflfm** [thunkable/thunkable-issues#130]
**Is your feature request related to a problem? Please describe.**
The WebAPI component does not currently support the PATCH method. This is a very common and important method.

**Describe the solution you'd like**
It should be pretty easy to implement since, code-wise it's really the exact same thing as POST

**Describe alternatives you've considered**
If one has control over the web server code, one can use the POST method instead, but PATCH is more appropriate in some cases and when one does not own the target server, this won't be an option at all.

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by amblemind** [comment]
Upvote: I'm using AirTable API calls more and more because they allow you to use the filterByFormula queryParam. Along with this, I'd like to be able to use a PATCH REST call, so that I can update a single cell rather than having to retain the whole row record and use a PUT. PUT removes any values not defined in the object passed.

**Comment by josmas** [comment]
we have this on testing; out soon if all goes well.

**Comment by amblemind** [comment]
@josmas This works wonderfully form me. Thanks!
https://youtu.be/7LO80MCvYCM?t=430
