### ISSUE TITLE
error parsing package

### ISSUE THREAD

**Issue by djpmp67** [thunkable/thunkable-issues#160]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Is this for Classic, Classic companion, ✕, ✕ Android companion, or ✕ iOS companion?

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What did you expect to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by djpmp67** [comment]
error parsing package??
My first application
android 7.1.1
https://x.thunkable.com/copy/47d1dd3580cb1eed2048cb7dbdb9d7c5

**Comment by mark-friedman** [comment]
@djpmp67 There is a bug in our system that creates an invalid "App (Bundle) ID" for your app.  As a workaround, please manually change that ID so that it's final component (i.e. after the last '.') begins with at least one letter.
![Screen Shot 2019-05-17 at 9 20 48 AM](https://user-images.githubusercontent.com/1743690/57942078-70cd5880-7885-11e9-85ad-8c8c57bd0898.png)

Click on your app name in the top left of the screen to open the App Settings.
