### ISSUE TITLE
Value read from Label.FontSize is NaN unless explicitly set

### ISSUE THREAD

**Issue by espertus** [thunkable/thunkable-issues#209]
### Platform
✕
✕ Android companion
✕ iOS companion

### Issue/Request Origin
A student wrote the program. I simplified it to isolate the unexpected behavior. (We were trying to write a program that would increase the label's font size by one on each button press.)

### Steps to Reproduce
1. Create a label and a button. Do not change default properties.
2. Write code so that when the button is pressed, the label's font size is written to the label's text field.
3. Run the program with Thunkable Live on Android or iOS (I tried both) and press the button.

See program: https://x.thunkable.com/copy/35dc0cbaf6d026a2d312553e4d9f9c15

### Expected Behavior
I expected the font size to be displayed as text in the label.

### Actual Behavior
The displayed value was NaN (not a number), not the actual font size.
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by mark-friedman** [comment]
@espertus, you are correct in your assessment of the situation.  The underlying issue here is that our property getters currently only return the value of a property if it is explicitly set (either in the designer or via blocks).  In the case of your program, since you didn't define the 'Font Size' property it has the value of `undefined` and adding one to it returns `NaN`.

The workaround, as you probably already realized, is to just set an initial value for the font size.

**Comment by jane-d-alt** [comment]
Hi there,

Apologies for not following up when this behavior was originally resolved.

In [this project ](https://x.thunkable.com/projectPage/609d40266cbfff00119d35d6/) there are 2 labels: one was dropped in as default, only the text was changed, the font size was not touched. One specifically had the font size wiped out. The first returns its default font size, 18, and the second returns null, which I had to actively set in its properties.

Thanks for reporting!
