### ISSUE TITLE
Pb with If control

### ISSUE THREAD

**Issue by franckled** [thunkable/thunkable-issues#302]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info the faster we will be able to address it!

### Platform
Thunkable X

### Issue/Request Origin
When I try to test a variable to find the lower one, it is impossible to find the minimum between 18  2 11 and 9. The code always choose 11 even if I put the number in a variable or If I use the text from an input aera.

![Capture d’écran 2019-11-14 à 15 10 42](https://user-images.githubusercontent.com/57760666/68864193-fde85180-06f0-11ea-98dd-9a6898608aea.png)

**Comment by mark-friedman** [comment]
The issue here is that the comparisons that are you are doing here are text/alphabetic comparisons rather than numeric comparisons.  In order to force your comparisons to be numeric you'll need to do something like add 0 to the text.

Here's an example of a simple app that demonstrates the difference: https://x.thunkable.com/copy/74960c6ef2add26b9c61560001cd3f38

And for convenience, here are the blocks from that app:

![Screen Shot 2019-11-14 at 10 53 35 AM](https://user-images.githubusercontent.com/1743690/68887384-c0260180-06cd-11ea-84f2-81543ce6942c.png)

We probably ought to have something like a `as Number` block that makes this a little easier and clearer.

-Mark

**Comment by franckled** [comment]
Hello
Thanks +++
You're right but I didn't know how to compare text and number in these two ways !
Thank you for the help

**Comment by mark-friedman** [comment]
Glad we could help!
