### ISSUE TITLE
Parsing package bug

### ISSUE THREAD

**Issue by ErDiezo** [thunkable/thunkable-issues#315]
Hi,
I have a problem when I try to build my app and install it on my phone. Every time, the build is successfully made but after the download, I have the error “there is a problem parsing the package”. I tried to build a simple app with only 1 label: it doesn’t work. I tried on different Google accounts: same. And it’s going this way since days ago. Does someone know how to fix this ?

**Comment by mark-friedman** [comment]
@ErDiezo What phone are you downloading the app to and what OS version is it running?

**Comment by ErDiezo** [comment]
@mark-friedman I tried on a Galaxy A3 (2017) with Android 8.0.0 and on a Galaxy S8 with Android 9

**Comment by mark-friedman** [comment]
@ErDiezo Have you enabled "downloading from unknown sources" on your phones (see [here](https://docs.thunkable.com/download#to-install-allow-apps-from-unknown-sources))?  Also, do you have an anti-virus apps installed on those phones?  If so, you may need to disable them.

**Comment by ErDiezo** [comment]
@mark-friedman I enabled it, and I don't have anti-virus. For the same app, I could install it like 2 weeks ago but now I can't. It was perfectly working before

**Comment by mark-friedman** [comment]
@ErDiezo Can you check and see if you can install your APK file on an emulator (see [here](https://docs.thunkable.com/emulators) for how to install an emulator)?

_Note that you can bypass the last step in the instructions above since yo don't need to install the Thunkable Live app for this test.  Also note that you can install your app on the emulator by dragging the APK file onto the emulator window once it is running _

**Comment by ErDiezo** [comment]
It doesn't work on the emulator BlueStacks

**Comment by mark-friedman** [comment]
@ErDiezo Can you post a link here to the project?

**Comment by ErDiezo** [comment]
https://x.thunkable.com/projects/5dda84f0a5c6b79d87283dd6/2e9ad61f-dae7-485b-ab07-b253f9954aba/designer

**Comment by mark-friedman** [comment]
@ErDiezo You said that you "tried to build a simple app with only 1 label: it doesn’t work".  Could you post a link to that simple app?

**Comment by ErDiezo** [comment]
@mark-friedman https://x.thunkable.com/projects/5de1052ddc47fe311e8e149d/8c5ef318-ce62-477a-88aa-b42f9785fef6/designer

**Comment by mark-friedman** [comment]
@ErDiezo In both of your apps the app name begins with a number.  While that is technically ok, it also means that the default generated app/bundle ID contains a segment (the parts separated by '.'s) that begins with a number and that is what is causing the problems.  If you edit your projects and change the app/bundle ID so that the last segment begins with a letter, everything should work fine.

See https://docs.thunkable.com/publish-to-play-store-android#app-info for how to get to the app settings in order to change the app/bundle ID.

**Comment by ErDiezo** [comment]
@mark-friedman thank you, it works!
But I have a second question (sorry?): I have a list viewer in my second screen but it doesn't display itself correctly. Do you know what can be the reason? I can see it perfectly in the Live App but in the app I just downloaded, it doesn't.

**Comment by mark-friedman** [comment]
> I have a list viewer in my second screen but it doesn't display itself correctly. Do you know what can be the reason? I can see it perfectly in the Live App but in the app I just downloaded, it doesn't.

@ErDiezo Could you please post your question in the community?  You'll get a larger set of people reading (and hopefully answering) it that way.

-Mark
