### ISSUE TITLE
Variables name changed to ID number and no longer working 

### ISSUE THREAD

**Issue by ayocarti** [thunkable/thunkable-issues#353]
Thunkable app was working fine until 5 mins ago when all my variables name changed automatically to ID number  and now variables are no longer working especially stored variables which have been having issues for the longest 

### Platform
Thunkable X

**Comment by mark-friedman** [comment]
@ayocarti We've made no changes to the service since last Friday.  I suspect that you are just running into a problem that actually started then.  Please see [our community post about our last release](https://community.thunkable.com/t/thunkable-x-blocks-update-your-feedback/425809/) to keep track of things.
