### ISSUE TITLE
(Thunkable X) Crash the app in Live on Android when you click the button

### ISSUE THREAD

**Issue by AlexITMan** [thunkable/thunkable-issues#375]
Open the app and select the Buttons option in the list. Оn the Buttons screen, click on the button in the form of a diamond or octagon-crash without a message.

https://x.thunkable.com/projects/5d70f93f8a62b4079eedaff2/project/properties/designer/

**Comment by josmas** [comment]
Thanks for the report @AlexITMan 
I was able to reproduce it; we will look into it!

**Comment by josmas** [comment]
@AlexITMan we've patched this up and it should be available in the next release (probably early next week). Thanks for the report. Will leave it open until we can confirm it's fixed.

**Comment by AlexITMan** [comment]
Thank you, we will wait for the result. For convenience, I created a bag-tracker where you can easily see bugs that cause crashes and other troubles. If you and the team are interested in this, do not hesitate to use the project - https://x.thunkable.com/projects/5dbd5243a77acad1b26f851f/project/properties/designer/

All these bugs were reported, but I think that they somehow got lost, and here everything is collected.

**Comment by josmas** [comment]
Hey @AlexITMan thanks for that!

It is actually very complicated for us to use a project with several bugs on it because we cannot isolate parts of it. So we cannot know what is causing what, or if there are any interactions among bugs or mixed behaviors. When we debug through it, we might know what we are looking for, but we don't what is causing the behaviors that we are seeing. It is much faster to have minimal projects with just one issue. But nonetheless, we really appreciate your help and reports, and we'll go through the project linked.
