### ISSUE TITLE
Map marker color

### ISSUE THREAD

**Issue by Shemantab** [thunkable/thunkable-issues#451]
It would be better if i can change map marker color in map.

**Which platform are you asking for?**
Thunkable ✕ (x.thunkable.com)

**Comment by rem708** [comment]
this has already been requested by myself in #335

**Comment by Bellacopia** [comment]
I add my voice to this request because I am trying to develop an app that shows some points of interest and the user's position on the map. 
And I absolutely need that the marker indicating the user's position (i.e. the location sensor) is green and not red like the others. 
It does not seem to me that it is an unjustified request! Indeed it seems to me that it is the bare minimum.`Thanks in advance.

**Comment by Bellacopia** [comment]
Is there anything new in this regard? As I said in my last message, it would be essential for me to be able to change the color of the marker indicating the user's position to green; is it really that complicated?

**Comment by AmigoDeluxe** [comment]
Yup... we need this :-)

**Comment by bymahoapp** [comment]
This is quite important. Can you attach this issue to nativeEvent null issue?

**Comment by AmigoDeluxe** [comment]
Let's make marker colours great again... please?  I would pay extra for that feature. And also to be able to update pins by referring to them instead of having to delete them all and re-creating them with their updated values.

**Comment by AmigoDeluxe** [comment]
https://github.com/react-native-maps/react-native-maps

**Comment by jane-d-alt** [comment]
Closing as this overlaps with #335. We appreciate that this is a feature that the community wants to see. If you agree with an existing request, we encourage you to comment on it.
