### ISSUE TITLE
Feedback on the request

### ISSUE THREAD

**Issue by grfr58** [thunkable/thunkable-issues#464]
Hello Thunkable staff, 
you decided to have the community as tester and provider of new feature.
I think is a good idea but when someone post a request if you don't give any feedback, like:

We will consider the request in the next future
We will consider but we don't know when
We will never work on the request
or even is a stupid request

I think person like me will stop to make request or suggestion because there is no feedback from you.

I am asking other thunkable user to subscribe this post.

Thanks
Francesco

**Comment by josmas** [comment]
Hi Franceso, we do our best to reply to all feature requests but we need to prioritise due to volume; we literally get hundreds of questions through the community, even more through Intercom, and a few here on github directly. We know that people that come to gihub are more tech savvy and understand more about the process of building software and how complex it can be. So we prioritise the other streams because of that.

Having said that, I do agree with you that we can do better, so we will create a few new tags on here such as `future work` or `to be considered` so we can go through tickets and provide some initial feedback faster. Thanks for your comment and excellent suggestion.

**Comment by grfr58** [comment]
Thank you I appreciate your answer.

In data 10 aprile 2020 12:33:04 Jos <notifications@github.com> ha scritto:
