### ISSUE TITLE
Local DB doesn't save modifications when app is closed.

### ISSUE THREAD

**Issue by sodart** [thunkable/thunkable-issues#497]
### Platform
X

### Steps to Reproduce
1. Make Local DB
2. Modify a cell using 'call SetCell'
3. close app
4. re-open app

### Expected Behavior
I expected the new cell value to be saved.

### Actual Behavior
The cell stays as the initial value.

**Comment by jane-d-alt** [comment]
Hi there,

This is the expected behavior of the Local DB component. See further info here: https://docs.thunkable.com/local-db#update-data-in-your-table

You can create a local Data Source in your app project: https://docs.thunkable.com/data-sources
Changes to a local Data Source will persist if you close and re-open the app.
