### ISSUE TITLE
iOS 13 dark mode compatibility

### ISSUE THREAD

**Issue by BatmanSup99** [thunkable/thunkable-issues#501]
Hello. I make a dark mode function to my applications and I was wondering since many of my users have iOS 13, can I make an option to set the background color based on the users state in light mode or dark mode?

**Comment by MrMazzone** [comment]
@BatmanSup99 I believe what might be a better request and still meet your needs is a block that retrieves the user's system wide theme selection (light/dark).  Since Android, iOS, Windows, and Mac now have this and many websites, browsers, and apps now take advantage of it.  Not sure how each OS reports this info, so could be harder to implement.  Maybe just iOS and Android support first. 

@BatmanSup99 would you be willing to change this issue's title to "Block to Retrieve User's System Wide Light/Dark Theme"?

**Comment by BatmanSup99** [comment]
Also, do you have a certain plan to adding support or creating a way to retrieve the user’s state?

Sincerely,
Almuthanna

**Comment by MrMazzone** [comment]
Hi Almuthanna (@BatmanSup99 ),
I am not on the Thunkable team.  I am hoping after you change the title, they may update us on adding this to their planned work.

Joe

**Comment by BatmanSup99** [comment]
Oh. Sorry got the misunderstanding 

Sincerely,
Almuthanna

**Comment by domhnallohanlon** [comment]
Hi @BatmanSup99 apologies for the delay getting back to you. 

The good news is that in the meantime we've release a block that now does this!
https://docs.thunkable.com/device#get-device-color-scheme

Hope that helps!

**Comment by BatmanSup99** [comment]
Thank you so much for the information. I’m glad that this is officially a feature!

Sincerely,
Almuthanna
