### ISSUE TITLE
Web API and airtable: QueryParameters - Block does not work any longer!

### ISSUE THREAD

**Issue by kezb765** [thunkable/thunkable-issues#518]
I have to re-open #131:
- the block "from WEB_API set QueryParameters" (ThunkableX) stopped to work!
- in march 2020 I wrote successfully an app with a dynamically generated filter to fetch data from an airtable, see:
![grafik](https://user-images.githubusercontent.com/7669660/81949529-3ff04280-9603-11ea-937b-8cdfd99247fe.png)

- Today this block does not work any longer. It replies with **all** datasets, unfiltered.

- On the other hand, entering this QueryParameter in the design-settings of a web_api component, the filter works! 

I want the QueryParameter set via block, because that way I can build _dynamic_ search filters, airtable does the work of filtering, and only the needed data gets transmitted from airtable to my app.

**Comment by MrMazzone** [comment]
@kezb765  What error are you getting from the Get request block?

**Comment by kezb765** [comment]
Hi @MrMazzone , I do not get an error. Let me explain the problem when using the Web_API.QueryParameter by a block (see picture above). Im my example the QueryParameter contains a filter for airtable. See also [https://blog.airtable.com/the-right-sort-of-api-updates/].

Lets assume that the table in airtable contains dozends of usernames in column "Name".
**- expected behaviour:**
-- I call Web_API.get and it returns a JSON-string, that contains **only** the rows where the filter applies, for example the rows, where "name" equals "user@example.com". Of course it could be that the JSON-response says, that there is no row which fits to the filter, but this is not an error.

**- actual result:**
-- I call Web_API.get and it returns a JSON-string, that contains **all** rows. No filter was performed. That means, that the QueryParameter-block got ignored.

I am pretty shure, that my app worked as expected some weeks ago.

**Comment by MrMazzone** [comment]
@kezb765 OK, now I see what is going on.  Didn't know you could use the formulas like that in the query. Very nice!

Not saying this is a fix, and understand that your way is much more efficient, but here is how I am checking for a particular email address (value in a column of the spreadsheet) to retrieve a row.  Have Thunkable perform the search after retrieving the entire column as a list.  This is what I have done with JS also because again didn't know about "filterByFormula". However, for this to work the column would need contain unique values, like email addresses. 

Example: Using email address to check for a stored password in a cell (I do not recommend anyone store user passwords this way!)
![image](https://user-images.githubusercontent.com/40954645/82070710-243c7900-96a3-11ea-91aa-93a7c43e8a24.png)

**Comment by kezb765** [comment]
Hi @MrMazzone , yes, this is the "standard way" to do searches. But as you said you have to retrieve all records, and then perform a local search within your app. That slows down the process a lot compared to retrieve only one record with the result.

**Comment by josmas** [comment]
@kezb765 a way to debug this would be to print your full query to a label and compare it with what happens when you place it in the designer. There's no reason for one to work if the other does not.

I don't know if this is your case, but if you can print the full URL you should be able to also paste it in the browser and see the response.

It is always good practice to use the `error` and `status` blocks that result from a Web call, but that is unrelated here.

**Comment by kezb765** [comment]
@josmas and @MrMazzone and to whom it may concern,

I found the bug, it sat in from of the computer monitor: I defined a QueryString in JSON-syntax, but the web_api.set QueryParameters likes to have it as an object:

![grafik](https://user-images.githubusercontent.com/7669660/82326736-967fc700-99dd-11ea-92cb-06eabf75a4eb.png)

I am happy, this technique works again. The idea came from "**jared**" in the thunkable community, also thanks to him.

...and of course I always check for status and error, my screenshot was shortened for the sake of clarity. The error is empty, because airtable responded with the complete, unfiltered data when using the wrong syntax.
