### ISSUE TITLE
My project don´t start!!!

### ISSUE THREAD

**Issue by carlosacsousa** [thunkable/thunkable-issues#52]
I can´t open the project, and I don´t see any mistake...

![screen 1 interface](https://user-images.githubusercontent.com/41520363/43467536-c73bb5c6-94d9-11e8-8e2c-845766ce29c6.PNG)
![screen 1](https://user-images.githubusercontent.com/41520363/43467537-c7675b9a-94d9-11e8-9c9e-25056c815904.PNG)
![screen 3 interface](https://user-images.githubusercontent.com/41520363/43467538-c7afec8e-94d9-11e8-9c26-e05c4d0d0cb4.PNG)
![screen 3](https://user-images.githubusercontent.com/41520363/43467539-c7d7a288-94d9-11e8-98fa-2b4b957ef62c.PNG)

carlosacsousa2@gmail.com

### Platform
 ✕ iOS companion?

**Comment by mark-friedman** [comment]
@carlosacsousa, Could you please [share with us](https://docs.thunkable.com/thunkable-cross-platform/share) as simple a version of your project as possible which demonstrates the problem?

I would note that for general app issues like this you can often get better results posting to the [Thunkable community ✕ forum](https://community.thunkable.com/c/thunkable-cross), since you'll have more people looking at it.  This issues site is better suited for specific platform bugs and feature requests.
