### ISSUE TITLE
Preview in web with API

### ISSUE THREAD

**Issue by jrabraga1968** [thunkable/thunkable-issues#520]
Hello !

### Platform
X Thunkable

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?

### Steps to Reproduce
1. Click "Entrar"
2. Next screen only appear "Acervo Vila Meeples" in preview web mode

### Project Link
https://x.thunkable.com/projects/5eb48f2778c92291c2a3afb7/c6737804-972f-4315-bef8-47c846c21344/designer

### Expected Behavior
The list viewer is filled with the result of my API query whem preview my app in web mode

### Actual Behavior
The list viewer is NOT filled with the result of my API query whem preview my app in web mode. Using the Thunkable App Live in my phone, works.
```
  STACK TRACE AND/OR SCREENSHOTS
![image](https://user-images.githubusercontent.com/37147059/82101307-91bbca00-96e2-11ea-87c3-68d8678b2cbd.png)
![thunkaable live app](https://user-images.githubusercontent.com/37147059/82101383-c0d23b80-96e2-11ea-89c2-d1610486594e.jpeg)

```
Thanks

**Comment by josmas** [comment]
hi @jrabraga1968 unfortunately this is a CORS issue. The server you are using to retrieve the json object does not allow requests from web sources (programmatic calls through http). There isn't anything we can do as we do not own the server.

Longer explanation of why it works on mobile but not on web ca be found [here](https://stackoverflow.com/questions/46802940/cors-issue-between-web-android-ios).

A couple of notes on your blocks:
1. the `response` that you get from the server on Web preview is not a json object, so the app crashes when you try to convert it into json. In this case, the server responds with a simple text saying `Failed to fetch`. Again, we cannot control what third party servers respond, so we cannot do anything about it.

2. before using a response you should always have an if block that checks for either the `error` or the `status`. In this case, the code would still crash because of the reason explained in 1, but if you catch these and print their to a label alongside response, it might help you debug the issue.

Thanks!
