### ISSUE TITLE
Text Box Error after Android Companion Version 203

### ISSUE THREAD

**Issue by KaneoheKid** [thunkable/thunkable-issues#619]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Thunkable Live, Android only, not iOS

### Issue/Request Origin
I noticed that some of my text boxes stopped displaying their "hints" and would only show a line of pixels when entering text.  This started after android companion version 203.  Up until about 2 weeks ago, there was not problem.  The problem surfaces when the user deletes the top and bottom padding numbers for the text box and does not type in a number.  There is a faint "0" in the background which makes the user think that the padding is set to zero.  However, when zero is entered into the top and bottom padding fields, the hint and text displays normally.  

This took me a long time to figure out, the difference between the fields that displayed properly and those that didn't was so subtle.  Recommend that you have the padding value default to "0" if there is nothing in the padding field.

### Steps to Reproduce
1. see this project:
https://x.thunkable.com/copy/3f065bb55bda6d42c91e70553a46b612

2. Notice that the top two text boxes are empty in the android companion.  Try typing something into them.
3.  enter "0" into the top and bottom padding fields for the top text box "FacilDamageTXT"
4.  Notice that now the hint shows and text displays as normal.  
5.  Delete the zeros just entered into the padding fields
6.  Notice that now the hint disappears and when you type all you see is a single row of pixels again
7.  If you type zero in the top padding and leave the bottom empty, or the reverse, the text will appear, but pushed to either the top or bottom. 

Again, this seems to be android only, not iOS or Preview or WebAPP.

**Comment by josmas** [comment]
Hi @KaneoheKid thanks for the report and thanks so very much for the very detailed walkthrough and sample project, that helps a ton.

It seems like the new version of the library we use for components is picky about types on Android. It used to take either a number or a string, but now it only works with numbers. We've seen this in a few other places, only for Android.

We'll have a look at the issue, thanks!

**Comment by josmas** [comment]
Hi again @KaneoheKid 
I was actually wrong in my comment above. One of the issues here is that your text boxes are too short (only 23 pixels in height).

With the faint zero values, if you set your text input height to 48 (or even less than that), you will see the hint again.

48 seems to be the recommended size for inputs according to the material design guidelines (https://material.io/components/text-fields#specs) otherwise some people will have trouble clicking into the element.

I am in two minds about setting the value back to 0px by default, because there is a difference between setting paddingTop: 0px; and not setting paddingTop at all (which would be the case with the faint zero value). Unfortunately iOS and Android seem to behave differently when paddingTop is not set, which reinforces my feeling that we should not force a value always and allow people to set the value or not depending on their needs. What do you think?

**Comment by KaneoheKid** [comment]
Josmas,

That is a tough situation, when it behaves a little differently on the two platforms.  Usually, if you set a default (i.e. 0 px) and it doesn't look right, people will then change it.  With this issue, one wouldn't realize what is going on unless they go through all of the troubleshooting that I did.  I tend to think that setting it at zero or 1 would be the best solution.

My apps have lots of user input data so I tend to make the text boxes smaller so that they are better organized on the small screen.  The fact that this hasn't been reported by others may be an indication that it isn't common and it might be enough to mention it in Documentation (although I have to admit that I didn't look in Documentation when trying to troubleshoot).

Sorry, this was probably not much help.

**Comment by jane-d-alt** [comment]
This issue was resolved shortly after reporting. You should not experience this behavior in current versions of the Thunkable Live app for Android. We will close this issue now; apologies for not following up when this behavior was originally resolved.
