### ISSUE TITLE
Web Viewer displays tiny result

### ISSUE THREAD

**Issue by MrTwoCanes** [thunkable/thunkable-issues#621]
### Platform
Thunkable X

### Issue/Request Origin
Where did you get this issue? Email, Intercom, or Community?
No idea what this means.

### Steps to Reproduce
1. Use Web Viewer interface
2. Upload HTML file
3. Fill URL file with HTML filename

### Project Link
https://x.thunkable.com/projects/5f1ccde365b8de41f815fe04/b14ab5e8-acbd-43b3-8320-0a8552a28fdf/designer

### Expected Behavior
I expect the HTML to display using the container size.  
### Actual Behavior
The resulting background seems outsized, but the actual HTML code is displayed very small in the upper left corner and needs manual strokes to enlarge image.  Happens with images as well as text-only.
```

Here is the Screen1 Design page:

![webviewerScreen1](https://user-images.githubusercontent.com/67872003/88833022-8545fa00-d186-11ea-997c-395bae8f572c.png)

Here is the result on my Samsung S6:

![webviewernoworkgood](https://user-images.githubusercontent.com/67872003/88832595-e8835c80-d185-11ea-89d6-4db12de0cc51.png)

**Comment by StevenPurn** [comment]
Hi! Sorry you're experiencing this issue. I'm wondering if it would be possible for you to share the html file that you're using so I can do some investigation into this. Is it consistently a problem or isolated to a single file? Have you always had this issue or did it recently change behavior?

**Comment by MrTwoCanes** [comment]
Hi Steven, 

I've tried a chart producing widget and a simple HTML file.  They both do the same thing.  I've had this issue since my initial attempt about 10 days ago.  Before today, the image would not show on the phone app at all.  (Samsung S6 & S9)  Occasionally the Preview would show the image as it is in my screenshot, usually it was blank too.

Thanks,
-Kevin


<div style="width:448px; border:1px solid #2D6AB4;height:auto;background-color:#FFFFFF;font-family:Arial,sans-serif;"><div style="background-color:#2D6AB4;width:100%; margin:0 auto;font-weight:bold;text-align:center; padding-top:0px;"><a href="https://www.goldpriceoz.com/silver/" style="font-size:34px; color:#FFFFFF;text-decoration:none;" rel="nofollow">Silver Price</a></div><script type="text/javascript" src="https://www.goldpriceoz.com/silverwidget.php?m=000000&g=FFFFFF&c=2D6AB4&i=FFFFFF&l=76A4FB&o=E6F2FA&w=450"></script></div>

---------------------------------------------------------------------------------------------------------------------------------------------------------------------
<html>
<head>
<title>
A Simple HTML Document
</title>
</head>
<body>
<p>This is a very simple HTML document</p>
</body>
</html>

**Comment by MrTwoCanes** [comment]
Sorry, didn't use code block first time.

`
<div style="width:448px; border:1px solid #2D6AB4;height:auto;background-color:#FFFFFF;font-family:Arial,sans-serif;"><div style="background-color:#2D6AB4;width:100%; margin:0 auto;font-weight:bold;text-align:center; padding-top:0px;"><a href="https://www.goldpriceoz.com/silver/" style="font-size:34px; color:#FFFFFF;text-decoration:none;" rel="nofollow">Silver Price</a></div><script type="text/javascript" src="https://www.goldpriceoz.com/silverwidget.php?m=000000&g=FFFFFF&c=2D6AB4&i=FFFFFF&l=76A4FB&o=E6F2FA&w=450"></script></div>

`

`<html>
<head>
<title>
A Simple HTML Document
</title>
</head>
<body>
<p>This is a very simple HTML document</p>
</body>
</html>
`

**Comment by MrTwoCanes** [comment]
Hi Steven,

I've tried a chart producing widget and a simple HTML file. They both do the same thing. I've had this issue since my initial attempt about 10 days ago. Before today, the image would not show on the phone app at all. (Samsung S6 & S9) Occasionally the Preview would show the image as it is in my screenshot, usually it was blank too.

Thanks,
-Kevin

```
<html>
<head>
<title>
A Simple HTML Document
</title>
</head>
<body>
<p>This is a very simple HTML document</p>
</body>
</html>

```
```
<!-- Silver Price Script - SILVERPRICEOZ.COM -->
<div style="width:448px; border:1px solid #2D6AB4;height:auto;background-color:#FFFFFF;font-family:Arial,sans-serif;">
<div style="background-color:#2D6AB4;width:100%; margin:0 auto;font-weight:bold;text-align:center; padding-top:0px;">
<a href="https://www.goldpriceoz.com/silver/" style="font-size:34px; color:#FFFFFF;text-decoration:none;" rel="nofollow">Silver Price</a></div>
<script type="text/javascript" src="https://www.goldpriceoz.com/silverwidget.php?m=000000&g=FFFFFF&c=2D6AB4&i=FFFFFF&l=76A4FB&o=E6F2FA&w=450"></script></div>
<!-- End of Silver Price Script -->

```

**Comment by MrTwoCanes** [comment]
Didn't mean to close it, hit the wrong button.

**Comment by StevenPurn** [comment]
Thanks for following up! I'm looking into this but don't have an update for you yet. I'll follow up again shortly once I have a better idea of what is going on and the timeline for a fix.

**Comment by MrTwoCanes** [comment]
Thank-you.  I guess I'll have to release the Beta with that not working.  It is literally the last item to check off.

But hey, no pressure! :-)

**Comment by StevenPurn** [comment]
Unfortunately, I don't think there is too much we can do to help you with this. Are you only targeting Android or do you plan on releasing to iOS as well? It seems like currently you can turn off the ScalePagesToFit property in the advanced panel and play with the sizing of your widget a bit to get it to look better on the initial load. But that doesn't change anything on iOS and it will likely be inconsistent across devices with different screen sizes/resolutions. The library we use to implement the webview on iOS and Android doesn't seem to support any other scaling or zooming programatically. Is there maybe another way for you to implement this feature in your app?

**Comment by MrTwoCanes** [comment]
Thank-you Steven, for looking into this problem.

As for another way to implement this feature, I'm certainly open to suggestions.  I'm initially
targeting Android, but I also wanted to release iOS down the road.

A few questions:
How can it work perfectly in the Design Screen and Previewer but not on the phone app?  

How come simple HTML is displayed tiny as well as a widget?  I've had trouble with JavaScript
widgets not displaying at all.  Does anything work for the web viewer?

Why is it available if it doesn't work correctly?

**Comment by StevenPurn** [comment]
Can you clarify what you mean by the previewer? Are you referring to running your project as a web app? If so, some of our web implementations and native (iOS & Android) implementations are different because there are libraries which only work on certain platforms. We try to avoid this when possible but sometimes there are no other options. This means that in some cases behavior can vary slightly between web and native apps. This is also true in the designer. When we first started, it wasn't possible to create a web app with React Native and Expo so we generally had to create a replica for each component which would run in a browser for you to be able to see anything in the designer. The phone preview in the designer is currently our best approximation as to what your app will look like on your device. We have some improvements in the works to make that experience more consistent.

HTML will render based on the styling that you provide. Widgets are generally designed to be dropped into a site and occupy a small area of the screen. Unfortunately, with the widget you're trying to use, the developers didn't give you a lot of options for how it is displayed since they generate a static script for you to use rather than just providing a source url or something similar. 

As I mentioned, widgets are meant to be inserted into web pages and not necessarily to be used alone as the entire webpage. If the html is constructed correctly I would expect most of them to work. If they are more flexible than the one you are using I would also expect you to get better sizing results by changing the css of the different dom nodes. 

I think the web viewer generally works well. The issue here isn't that the web viewer doesn't work; it is that we don't have the ability to alter the styling for your widget since it is generated at runtime. If you open your html file with the chart in a web browser you will see that there is a lot of html generated by the script that is attached. It seems like they are referencing a script they've written which is hosted on their site and generating a google chart with the data. I'm guessing they have some automated job running on their server to update the numbers each day.  It would be much easier to create a solution if they just exposed their data via an API. You would be able to create your own html which can hit the API and generate a chart and render it to just fill the visible page which would give you exactly what you want. But it doesn't seem like they have an API and they don't give you the option for custom styling on the widget, they've made it very difficult to work with. 

It does work correctly in most cases. If you try and use the web viewer with most websites they will work as expected. You can run into issues occasionally when there are APIs being used that aren't supported by the web viewer but that tends to be rare. Obviously no component is perfect and we have limitations based on libraries that we use. 

In regards to other potential solutions I think there might be a few we could explore. There are some APIs which will give you data on the pricing of various metals though there are restrictions on the free tiers. You could potentially use one of those APIs to insert the data into a Google Sheet and then create your own html file which displays a chart from that Google Sheet and expands to fill the browser. Another options is to potentially attempt to write a script which runs after the widget's script and adjusts the sizing of their widget. I know that this would take more steps so I'm sorry that there doesn't seem to be a better option at the moment but we don't have control over the implementation of the widget from another site.

**Comment by MrTwoCanes** [comment]
Thank-you for your suggestions and clarifications.
