### ISSUE TITLE
Label Horizontal Alignment property does not work on Web

### ISSUE THREAD

**Issue by DrTedGit** [thunkable/thunkable-issues#657]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
X Web

### Issue/Request Origin
Found it on my own

### Steps to Reproduce
1. Create a label
2. Set Label width = Fill Container
3. Set Label Horizontal Alignment = Center
4. Go to blocks and add On Open Event
5. Set Label Text = Label TextAlign
6. Preview or Live Test to display

### Project Link
https://x.thunkable.com/copy/453fbfc519eb4357b9cd41cebb3871a9

### Expected Behavior
I expect the text to align according to the property (center). Text property aligns using Thunkable app on Android

### Actual Behavior
TExt aligned to the left
![image](https://user-images.githubusercontent.com/66176281/92415477-e8c03180-f10d-11ea-8e2b-0fe5fcb30c2f.png)

**Comment by MrMazzone** [comment]
I have observed this also.  Text Alignment does not work on the web.  

A workaround for now is that you can change some of the alignment properties in the Advanced --> Position category.

**Comment by jane-d-alt** [comment]
Hi there,

This issue has been resolved. You can see a published web app with a Label whose text is centered here: https://thunkable.site/web-build/index.html?webAppId=-HZ-wcFoU

We acknowledge other issues with Labels and web apps needs to be addressed (namely, that Labels need to have a Width = 100% rather than Fill Container at the moment). As this particular issue relating to text alignment has been resolved, we will close this issue. 

Thanks,
Jane
