### ISSUE TITLE
Share image bug

### ISSUE THREAD

**Issue by Irwin2004** [thunkable/thunkable-issues#806]
### Platform
Thunkable Live, version 254

### Issue/Request Origin
I use data viewer to show my image, I insert the image using airtable. Then I use share component and I add some blocks. But when I press the share button that I've made, the share option doesn't appear.
When I try to share text that insert using airtable and display it using data viewer, it works correctly and it show the share option.

### Steps to Reproduce
1. Open Thunkable Live
2. Press share button

### Expected Behavior
The share option will appear.

### Actual Behavior
The share option doesn't appear.

**Comment by josmas** [comment]
Hi there, can you please link to a project that reproduces this issue? Not asking for your projects as such, but a minimal sample projects that shows the issue. thanks!

**Comment by Irwin2004** [comment]
Hi @josmas, here is the link
https://x.thunkable.com/copy/0c3d4f704ec21d854fa897074f79be96
To share image click the image and click the text to share the text. When press the text, it shows the share option. But when press the image, it don't show the share option. The blocks it same between the text and image.

**Comment by josmas** [comment]
Hi @Irwin2004 can you confirm that this is exclusively when wanting to share an image from a data viewer?
An Image component works fine, right? I created a small app and it works for me, but we can look at the data viewer case.

**Comment by Irwin2004** [comment]
Hi @josmas, I want to share image using data viewer but I input the image using airtable. Can please you share your app.

**Comment by josmas** [comment]
Hi @Irwin2004 my app did not use the data viewer; so far I only checked that the share component works normally with the Image component on uploaded assets.

Are you testing this on Android or iOS?

There are a couple of things to test here, as mentioned above android and iOS behave slightly different, and I am not sure if one can share an image on Android that is a URL (you can share something that you have uploaded to the app, but not sure about http images). So if that works fine with an image component then we need to track why it would not work for a data viewer. Also, can you please confirm you are using a custom layout for the data viewer? because that could also be a factor.

**Comment by Irwin2004** [comment]
Hi @josmas, I am testing using Android and I use custom data viewer.

**Comment by josmas** [comment]
Hi @Irwin2004 thanks for confirming. Your app is working fine on iOS, I can click on both the image and text and they are shared correctly. But it does not seem to work on Android. We will have a look; thanks!

**Comment by Irwin2004** [comment]
Hi @josmas, have you finish fixing this issue? Could you inform me if it fixed?

**Comment by Irwin2004** [comment]
Hi @StevenPurn, could you check this bug?

**Comment by StevenPurn** [comment]
Yes, I'll look into this issue.

**Comment by StevenPurn** [comment]
I did some digging on this and it seems like it is actually just a bug with `ShareImage` on Android which doesn't seem to work with urls. So the good news is that there is nothing technically wrong with your data/data viewer/layout/etc. We will need to look into fixing the issue with the `ShareImage` function on Android to support images from urls.

**Comment by Irwin2004** [comment]
Thanks for your updates @StevenPurn
