### ISSUE TITLE
Time and Date Picker Opening Values

### ISSUE THREAD

**Issue by KaneoheKid** [thunkable/thunkable-issues#854]
**Is your feature request related to a problem? Please describe.**
The time and date pickers open with the time or date that the app was opened.  For example, if the app is opened at 10:00 AM on 3/20/21, the time and date pickers will start with those dates/times every time until the app is restarted.  Hence, if the user is using the time picker for data entry all day long, it will always pop up with 10:00 AM.

Also, the date and time pickers don't seem to work in the Web App.  Not sure if it is just my case or universal, but it is not mentioned in the unsupported components section of the documentation.

**Describe the solution you'd like**
It would be preferable for the default starting point to be the current date/time instead of the app opening date/time.

**Describe alternatives you've considered**
none

**Which platform are you asking for?**
Thunkable X, android, iOS and Web App.

**Additional context**
This simple project demonstrates the issue.
https://x.thunkable.com/copy/777147f68382299a27341ee8c1730508

**Comment by jane-d-alt** [comment]
Hi there,

If you want to update the default value of these components during app runtime, you will need to add blocks to make these updates.

If this behavior affected Time Inputs that were created during app runtime with Clone or Create blocks, then this behavior appears to have been resolved: a Time Input created with a Clone or Create block during app runtime will show the current time, even if it was cloned from a Time Input showing an earlier time.

Thanks for reporting the behavior relating to the Time Input and Date Input not behaving as expected in published web apps or when previewing a project on the web. This behavior has since been resolved.

Since the reported behavior appears to be resolved, we will close this issue for now. Please reach out if you have any other issues with these components.

Thanks for reporting!
