### ISSUE TITLE
Issue with Stack Navigator Screen

### ISSUE THREAD

**Issue by JacobCooper14** [thunkable/thunkable-issues#89]
Hi Thunkable Team,

I have created an example application here of the problem I am experiencing https://x.thunkable.com/copy/493095682b9dc2faee9eea3f24f77aa4

Basically I am using a stack navigator layout in modal mode with no headers in my app. What I expected to happen - and what was happening previously was that when triggered the child screen of the stack navigator would appear from bottom to top. 

Now when I do it the screen does not appear at all - I'm not sure if this is a recent layout issue - but it has effected multiple apps of mine,

Cheers
Jacob

**Comment by mark-friedman** [comment]
AFAICT, this is working as intended.  You cannot navigate forward between screens in different navigators.  One way to fix your issue would be to move `Screen1` into your Screen Navigator.  Alternatively, you could have your button in Screen1 navigate to `Stack Navigator1` rather than `Screen2`

I'm not sure why this might have worked previously.  If so, it was not supposed to ;-)
