### ISSUE TITLE
Offset Logo 

### ISSUE THREAD

**Issue by Danieljsmith1011** [thunkable/thunkable-issues#966]
**Is your feature request related to a problem? Please describe.**
I'm trying to make it so that the logo will be pretty much directly below the top left button, but am running into some trouble. 

**Describe the solution you'd like**
I want the logo to look pretty much exactly like it looks in the editor. 

I'm not sure how to get it to look like how it looks in the editor. When I hit preview or do a live preview the logo is not how I want it.

**Describe alternatives you've considered**
I have tried making the margins a negative number to try and move it up. The problem with that is that the logo positioning's on the different screens are different and it wont work. 

**Which platform are you asking for?**
Thunkable (share link)
https://x.thunkable.com/copy/d2f3240067b119dd192262619d91dab5

**Additional context**
![image](https://user-images.githubusercontent.com/85645847/121918954-28025b00-ccfc-11eb-8f70-fbbaa5782288.png)

![IMG-9608](https://user-images.githubusercontent.com/85645847/121920132-59c7f180-ccfd-11eb-857c-851d9f949436.PNG)
 (iphone live view)

![IMG-9609](https://user-images.githubusercontent.com/85645847/121920218-72d0a280-ccfd-11eb-9b1e-61d79f871233.jpg)
 (android live view)

**Comment by jane-d-alt** [comment]
Hi there,

Thanks for reporting this behavior. 

It looks like the Height of your Image component is set to 'fit contents'. It also looks like your image file is very large!
Your image component is trying to be as tall as this image file, which is why it takes up all of your screen - add a Border to your Image component to see what I mean.
<img width="404" alt="Screen Shot 2021-06-25 at 10 42 20 AM" src="https://user-images.githubusercontent.com/51848939/123405742-07f75500-d5a2-11eb-8760-ed9b1324e97c.png">

Since your Image Resize Mode is set to 'contain', you don't see how tall your Image component is!

To fix this, simply change your Image component's Height to an absolute value (like 200px).

You can also try this: 
- set the Row that contains your image component to have an absolute height (200px) or a Height that doesn't depend on the Image component's Height, like 10% of the Screen
- set your Image component's Height to 'fill container'.

Either of these options will prevent your Image component from being as tall as your image file, which should improve its appearance.

I hope this helps! Let me know if this works for you.
